Corrected Limelight Equations
HoltRobotics/2024RobotV2 pull request #11
Opened 2024-03-09 04:03 UTC by isaiah-g04

Corrected the distanceToArmAngle equation, even after fixing the distances the shooter equation stayed the same so that one is unchanged.

2024-03-10 02:49 UTC, Nixis198 commented
@isaiah-g04 can you commit the changes we made today?

2024-03-10 18:33 UTC, isaiah-g04 commented
@Nixis198 just did. Made some changes to the shooting equation command, the distance wasn't being referenced as a double supplier so me and Jay fixed that.

2024-03-10 19:06 UTC, Nixis198 requested changes
Over all the things we needed to do to make this all work kinda killed me inside, but that's robotics for you.
I left comments where things needed to be fixed. You don't have to delete all the print statements if you don't want to/want to keep them for testing.
But the major thing to change is moving `distanceToRPM()` to the Limelight subsystem and updating all the command that use that method.
We really should go through and add comments to our subsystems, commands, and methods, but that's not too important.

2024-03-10 19:06 UTC, Nixis198 commented on src/main/java/frc/robot/commands/Combo/AutoShoot.java
> +        // new PrintCommand("Distance: " + light.getDistance() + " Angle: " + (15.8 + (19.3 * light.getDistance()) + (-2.51 * Math.pow(light.getDistance(), 2)))),
If this command is working now, we can delete this PrintCommand().

2024-03-10 19:06 UTC, Nixis198 commented on src/main/java/frc/robot/commands/Shooter/AutoRPM.java
> +    // System.out.println(m_shooter.distanceToRPM(() -> m_light.getDistance()));
We can also delete this print line.

2024-03-10 19:06 UTC, Nixis198 commented on src/main/java/frc/robot/subsystems/Shooter.java
We really shouldn't have to define a subsystem in a subsystem. It will be better to move distanceToRPM() to the Limelight subsystem instead of having it in the Shooter subsystem. We already have the distanceToArmAngle() method in the Limelight subsystem so let's just keep all of the conversions in the Limelight subsystem.

2024-03-12 20:29 UTC, Nixis198 approved these changes

2024-03-12 20:30 UTC, merged